(defun stringify (x)
  (if (callable? x)
      (+ x "")
      (try
       (js-code "JSON.stringify(d$$x)")
       "'**UNABLE-TO-STRINGIFY**'")))

(defun literal(k)
  (stringify (js-code "lisp_literals[parseInt(d$$k.substr(1))]")))

(defun variable(k)
  (stringify (js-code "glob['d'+d$$k]")))

(defun symbol(k)
  (stringify (js-code "glob[d$$k]")))

(defun fclosure (x)
  (do ((result (js-object))
       (vars (js-object))
       (todo (list x))
       (litout false))
      ((empty todo)
         (let ((output (list)))
           (dolist (k (sort (keys vars)))
             (cond
               ((= (aref k 0) "q")
                (unless litout
                  (setf litout true)
                  (push "lisp_literals=[];" output))
                (push ~"lisp_literals[{(slice k 1)}]={(literal k)};" output))
               ((= (aref k 0) "s")
                (push ~"{k}={(symbol k)};" output))
               ((not (undefined? (js-code "glob['d'+d$$k]")))
                (push ~"d{k}={(variable k)};" output))))
           (dolist (k (sort (keys result)))
             (push ~"f{k}={(aref result k)};" output))
           output))
    (let ((new-todo (list)))
      (dolist (x todo)
        (setf (aref result (. x name))
              (or (and (symbol-function x)
                       (+ (symbol-function x) ""))
                  "**N/A**"))
        (dolist (v (or (and (symbol-function x)
                            (. (symbol-function x) usedglobs))
                       (list)))
          (setf (aref vars v) true))
        (dolist (fn (or (and (symbol-function x)
                             (. (symbol-function x) outcalls))
                        (list)))
          (unless (aref result fn)
            (let* ((i (index "$$" fn))
                   (y (intern (demangle fn) (slice fn 0 i))))
              (push y new-todo)))))
      (setf todo new-todo))))

(defun minimize (s)
  (let ((seen (js-object))
        (count 0))
    (labels ((nstr (x)
               (if (< x 62)
                   (aref "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789" x)
                   (+ (nstr (floor (/ x 62)))
                      (nstr (% x 62)))))
             (newname (x)
               (or (aref seen x)
                   (setf (aref seen x)
                         (+ "$" (nstr (1- (incf count))))))))
      (setf s (replace s "[a-zA-Z0-9]*\\$\\$[a-zA-Z0-9_$]*" #'newname))
      (setf s (replace s "f\\.usedglobs=\\[[^\\]]*\\];f\\.outcalls=\\[[^\\]]*\\];" ""))
      s)))

(setf (symbol-macro (intern "main" ""))
      (lambda (&rest args)
        `(progn
           (let ((res ""))
             (dolist (x (fclosure ',#main))
               (incf res x))
             (incf res (js-compile '(funcall #',#main ,@args)))
             (display (minimize res)))
           null)))
