(defun make-clock (tx ty)
  (let ((clock (sprite *root*
                       (begin-path)
                       (circle 0 0 120)
                       (fill "#FFFFFF")
                       (stroke "#000000" 2))))
    (dotimes (i 60)
      (let ((t (/ (* 2 pi i) 60)))
        (add-graphics clock
                      (begin-path)
                      (circle (* 110 (cos t))
                              (* 110 (sin t))
                              (if (= 0 (% i 5)) 4 2))
                      (fill "#808080"))))
    (set-translation clock tx ty)
    (labels ((arm (w r)
               (sprite clock
                       (begin-path)
                       (move-to 0 (- w))
                       (line-to r -1)
                       (line-to r 1)
                       (line-to 0 w)
                       (close-path)
                       (stroke "#000000" 1)
                       (fill "#C0C0C0"))))
      (let ((hours (arm 8 80))
            (minutes (arm 6 100))
            (seconds (arm 4 115)))
        (sprite clock
                (begin-path)
                (circle 0 0 15)
                (stroke "#000000" 1)
                (fill "#FFFFFF"))
        (labels ((update ()
                   (let* ((d (js-code "(new Date)"))
                          (h (funcall (. d getHours)))
                          (m (funcall (. d getMinutes)))
                          (s (funcall (. d getSeconds))))
                     (set-rotation hours (- (/ (* 2 pi h) 12) (/ pi 2)))
                     (set-rotation minutes (- (/ (* 2 pi m) 60) (/ pi 2)))
                     (set-rotation seconds (- (/ (* 2 pi s) 60) (/ pi 2))))))
          (update)
          (set-interval #'update 1000))))
    (setf (sprite-hit clock) (drag clock))
    clock))
