(defun start-server (address port handler)
  (let* ((http (js-code "require('http')"))
         (server (funcall (. http createServer) handler)))
    (funcall (. server listen) port address)))

(defun my-handler (request response)
  (let ((url (. request url))
        (parms null))
    (when (find "?" url)
      (let ((i (index "?" url)))
        (setf parms (slice url (1+ i)))
        (setf url (slice url 0 i))))
    (let ((content (try (get-file (+ "." url) null)
                        (try (str-value (apply (symbol-function (intern (slice url 1)))
                                               (split parms "&")))
                             (str-value *exception*))))
          (ctype (cond
                   ((find ".html" url)
                    "text/html")
                   ((find ".css" url)
                    "text/css")
                   ((find ".js" url)
                    "text/javascript")
                   ((find ".jpg" url)
                    "image/jpeg")
                   ((find ".png" url)
                    "image/png")
                   (true "text/plain"))))
      (display ~"{url} --> {ctype}")
      (funcall (. response writeHead)
               200 (js-object ("Content-Type" ctype)))
      (funcall (. response end) content))))

(defun square (x)
  (let ((value (parse-value x)))
    (* value value)))

(defun lisp (x)
  (eval (parse-value (uri-decode x))))

(start-server "127.0.0.1" 1337
              #'my-handler)
