(import * from html)

(defun main ()
  (base-css "examples/base.css")
  (let** ((view (document.body.appendChild (create-element "div")))
          (board (make-array (list 3 3) "-"))
          (color 0)
          (#'new-game ()
            (setf board (make-array (list 3 3) "-"))
            (setf color 0)
            (dotimes (i 3)
              (dotimes (j 3)
                (setf (. ##~"c{i}{j}" src) (logo i j)))))
          (#'logo (r c)
            ~"img/{(aref board r c)}.png")
          (#'login-view ()
            (setf view.innerHTML (template "examples/login.html"))
            (focus ##user))
          (#'check-password ()
            (if (and (= ##user.value "agri")
                     (= ##password.value "pw"))
                (main-view)
                (progn
                  (focus ##user)
                  (show ##errmsg text: "Invalid user/password" delay: 2000))))
          (#'main-view ()
            (setf view.innerHTML (template "examples/main.html"))
            (dotimes (i 3)
              (dotimes (j 3)
                (let ((cell ##~"c{i}{j}"))
                  (on cell mousedown
                    (setf (aref board i j) (aref "ox" color))
                    (setf color (- 1 color))
                    (setf cell.src (logo i j))))))))
    (login-view)))

(main)
