(import * from html)

(defun main ()
  (base-css "examples/base.css")
  (let** ((view (document.body.appendChild (create-element "div")))
          (board (make-array (list 3 3) "-"))
          (color 0)
          (#'new-game ()
            (setf board (make-array (list 3 3) "-"))
            (setf color 0)
            (main-view))
          (#'logo (r c)
            ~"<img id=\"c{r}{c}\" src=\"img/{(aref board r c)}.png\">")
          (#'login-view ()
            (setf view.innerHTML (template "examples/login.html"))
            (focus ##user)
            (on ##ok click
              (if (and (= ##user.value "agri")
                       (= ##password.value "pw"))
                  (main-view)
                  (progn
                    (focus ##user)
                    (show ##errmsg text: "Invalid user/password" delay: 2000)))))
          (#'main-view ()
            (setf view.innerHTML (template "examples/main.html"))
            (dotimes (i 3)
              (dotimes (j 3)
                (let ((cell (document.getElementById ~"c{i}{j}")))
                  (on cell mousedown
                    (setf (aref board i j) (aref "ox" color))
                    (setf color (- 1 color))
                    (main-view)))))
            (on ##logout click (login-view))
            (on ##new click (new-game))))
    (login-view)))

(main)
