(import * from gui)
(defconstant SZ 128)
(defconstant MASK (1- (* SZ SZ)))
(defconstant SF 2)
(import * from layout)
(import * from graphics)

(defun life ()
  (let** ((w (window 0 0 (+ (* SZ SF) 40) (+ (* SZ SF) 100)
                     title: "The Game of Life"))
          (field (make-array (* SZ SZ) 0))
          (display (add-widget w (set-style (create-element "canvas")
                                            position "absolute"
                                            px/width (* SF SZ)
                                            px/height (* SF SZ))))
          (start/stop (add-widget w (button "Start/stop" #'start/stop)))
          (clear (add-widget w (button "Clear" #'clear)))
          (random (add-widget w (button "Random" #'random)))
          (run-timer null)
          (#'recalc ()
            (let ((new-field (slice field)))
              (dotimes (i (* SZ SZ))
                (let ((n (+ (aref field (logand (- i (1+ SZ)) MASK))
                            (aref field (logand (- i SZ) MASK))
                            (aref field (logand (- i (1- SZ)) MASK))
                            (aref field (logand (- i 1) MASK))
                            (aref field (logand (+ i 1) MASK))
                            (aref field (logand (+ i (1- SZ)) MASK))
                            (aref field (logand (+ i SZ) MASK))
                            (aref field (logand (+ i (1+ SZ)) MASK)))))
                  (if (/= n 2)
                      (setf (aref new-field i)
                            (if (= n 3) 1 0)))))
              (setf field new-field)
              (refresh)))
          (#'refresh ()
            (setf display.width (* SF SZ))
            (setf display.height (* SF SZ))
            (with-canvas display
              (let ((p 0))
                (dotimes (y SZ)
                  (dotimes (x SZ)
                    (fill-style (if (aref field p) "#000000" "#FFFFFF"))
                    (fill-rect (* SF x) (* SF y) SF SF)
                    (incf p))))))
          (#'start/stop ()
            (if (null? run-timer)
                (setf run-timer (set-interval #'recalc 10))
                (progn
                  (clear-interval run-timer)
                  (setf run-timer null))))
          (#'random ()
            (dotimes (i (* SZ SZ))
              (setf (aref field i) (random-int 2)))
            (refresh))
          (#'clear ()
            (dotimes (i (* SZ SZ))
              (setf (aref field i) 0))
            (refresh)))
    (set-layout w (V spacing: 8 border: 8
                     :filler:
                     size: (* SF SZ)
                     (H :filler: size: (* SF SZ) (dom display) :filler:)
                     :filler:
                     size: 30
                     (H :filler:
                        size: 80 (dom start/stop) (dom clear) (dom random)
                        :filler:)))
    (setf w.close-cback
          (lambda () (when run-timer (start/stop))))
    (random)
    (show-window w center: true)))

(defun main ()
  (life))

(main)
